### ISSUE TITLE
Setup cross-compiling CI/CD to make binary distributions for manylinux, macOS, and Windows available

### ISSUE THREAD

**Issue by pirate** [openzim/python-libzim#25]
Currently the `release.yml` Github Action relies on a binary build of `libzim.so` that is only available for `x86_64-linux-gnu`, and so `python-libzim` can only be made available on PyPI as a `bdist` (binary release) for that platform.

In order to support all the Linux distros, macOS, and Linux seamlessly with prebuilt `bdists`, the most modern recommended way that I could find for Cython packages (as of 2020-04) is something like this:

**`multi_release.yml`:**
```yaml
on:
  release:
    types: [published]
    tags:
      - v*

manylinux-release-wheel:
  name: Build release wheels for manylinux2010
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Build manylinux2010 wheels
      run: |
        # bdist_wheel gets built inside manylinux docker container to maximize compatibility
        docker run -e manylinux2010 bash -c '
          # e.g. something like this, this could be a script instead though
          python3 -m pip install cython wheel setuptools
          python3 setup.py build_ext
          python3 setup.py bdist_wheel
        '

        # Then wheels are further cleanud up in a 2nd step to make sure they link correctly
        python3 -m pip install -U auditwheel
        for f in artifacts/*.whl; do
          auditwheel repair --plat manylinux2010_x86_64 $f
        done
        ls -al wheelhouse/

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}-wheels
        path: wheelhouse

macos-release-wheel:
  name: Build release wheels for macOS
  runs-on: macos-latest
  strategy:
    matrix:
      python-version: ['3.6', '3.7', '3.8']
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build macOS wheels
      if: github.event_name == 'release'
      run: |
        python3 --version
        python3 -m pip install cython wheel setuptools
        python3 setup.py build_ext
        python3 setup.py bdist_wheel
        
        # Do any needed wheel cleanup here (delocate-wheel is similar to auditwheel)
        for f in bdist/*.whl; do
          delocate-wheel -w wheelhouse $f
        done

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}-wheels
        path: wheelhouse

windows-release-wheel:
  name: Build release wheels for Windows
  runs-on: windows-latest
  strategy:
    matrix:
      python-version: ['3.6', '3.7', '3.8']
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Build Windows wheels
      shell: bash
      if: github.event_name == 'release'
      run: |
        python -m pip install cython wheel setuptools
        python3 setup.py build_ext
        python3 setup.py bdist_wheel

        # Do any needed wheel cleanup here e.g. auditwheel equivalent for Windows

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}-wheels
        path: artifacts

upload-wheels:
  name: Publish wheels to PyPi
  needs: [manylinux-release-wheel, macos-release-wheel, windows-release-wheel]
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/download-artifact@v1
      with:
        name: Linux-wheels
        path: Linux-wheels
    - uses: actions/download-artifact@v1
      with:
        name: macOS-wheels
        path: macOS-wheels
    - uses: actions/download-artifact@v1
      with:
        name: Windows-wheels
        path: Windows-wheels
    - run: |
        set -e -x
        mkdir -p dist
        cp Linux-wheels/*.whl dist/
        cp macOS-wheels/*.whl dist/
        cp Windows-wheels/*.whl dist/
        ls -la dist/
        sha256sum dist/*.whl

    - uses: pypa/gh-action-pypi-publish@master
      if: github.event_name == 'release'
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
```

Further reading:

 - https://github.com/tensorflow/addons/blob/master/.github/workflows/release.yml
